-- Attendance System - Supabase schema
-- Chay toan bo file nay mot lan trong Supabase SQL Editor.
-- App ket noi bang secret key hoac legacy service_role key; khong dua key vao frontend.

create table if not exists public.attendance_periods (
  id text primary key,
  factory text not null default 'factory1',
  month integer not null check (month between 1 and 12),
  year integer not null check (year >= 2000),
  label text not null default '',
  source_filename text not null default '',
  source_path text not null default '',
  output1_path text not null default '',
  output2_path text not null default '',
  sheet_name text not null default '',
  block_count integer not null default 0,
  result_cells integer not null default 0,
  missing_cells integer not null default 0,
  late_cells integer not null default 0,
  manual_check_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_monthly_records (
  id bigint generated by default as identity primary key,
  period_id text not null references public.attendance_periods(id) on delete cascade,
  employee_code text not null,
  employee_name text not null default '',
  total_hours double precision not null default 0,
  work_days double precision not null default 0,
  monthly_salary double precision,
  daily_salary double precision not null default 0,
  hourly_salary double precision not null default 0,
  standard_work_days double precision not null default 26,
  bonus double precision not null default 0,
  advance_or_penalty double precision not null default 0,
  final_salary double precision not null default 0,
  note text not null default '',
  unique (period_id, employee_code)
);

create table if not exists public.employee_daily_records (
  id bigint generated by default as identity primary key,
  period_id text not null references public.attendance_periods(id) on delete cascade,
  employee_code text not null,
  day integer not null check (day between 1 and 31),
  punches jsonb not null default '[]'::jsonb,
  work_value text,
  missing_count text,
  late_minutes integer,
  manual_checks jsonb not null default '[]'::jsonb,
  review_notes jsonb not null default '[]'::jsonb,
  unique (period_id, employee_code, day)
);

create index if not exists idx_attendance_period_month
  on public.attendance_periods(factory, year, month);
create index if not exists idx_employee_monthly_code
  on public.employee_monthly_records(employee_code);
create index if not exists idx_employee_daily_lookup
  on public.employee_daily_records(employee_code, period_id, day);

alter table public.attendance_periods enable row level security;
alter table public.employee_monthly_records enable row level security;
alter table public.employee_daily_records enable row level security;

insert into storage.buckets (id, name, public)
values ('attendance-submissions', 'attendance-submissions', false)
on conflict (id) do update set public = excluded.public;

-- service_role/secret key bypasses RLS. Khong tao policy public cho du lieu cham cong.
